import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navBar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* all page will shown  from this children   */}
        {/* for pages we use page.jsx but if we use components we should always name it by their components (important!) */}
        {/* // nextjs not showing image directly it caching the image and showing it */}

        {/* .we can use fill on in image tag if we want to pass css from above div css styles.image */}
        {/* we can make layout for particular pages also always remember if there is page.jsx and layout.jsx then layout will render */}

        <Navbar/>
        <div className='container'>
        {children}

        </div>
        <Footer/>
        </body>
    </html>
  );
}
